FROM prom/alertmanager

LABEL maintainer="artemervits at gmail dot com"
LABEL version="1.0"
LABEL description="alertmanager container"
ENV REFRESHED_AT 2022_01_27

COPY alertmanager.yml .
COPY rules .
