FROM postgres:15.1

LABEL maintainer="artemervits at gmail dot com"
LABEL version="1.0"
LABEL description="postgresql container"
ENV REFRESHED_AT 2023_04_17

COPY tpcb-original.sql .
COPY tpcb-cockroach.sql .
