FROM postgres

LABEL maintainer="artemervits at gmail dot com"
LABEL version="1.1"
LABEL description="postgresql container"
ENV REFRESHED_AT 2023_09_21

COPY tpcb-original.sql .
COPY tpcb-cockroach.sql .
