FROM postgres:13.0

LABEL maintainer="artemervits at gmail dot com"
LABEL version="1.0"
LABEL description="postgresql container"
ENV REFRESHED_AT 2022_12_21

COPY tpcb-original.sql .
COPY tpcb-cockroach.sql .
