version: '3.8'

volumes:
  certs-roach-0:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:v20.1.3
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-0:/certs
    depends_on:
      - roach-cert
