version: '3.8'

# adding hard-coded IP addresses for each node as we need /etc/hosts populated with `cockroach` IP for
# kerberos to work

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-cockroach:/certs/cockroach
      - certs-client:/certs/client

  kdc:
    container_name: kdc
    hostname: kdc
    build: ./kdc
    volumes:
      - ./kdc/start.sh:/start.sh
      - keytab:/keytab
    depends_on:
      - roach-cert
    networks:
      roachnet:
        ipv4_address: 172.28.1.3

  cockroach:
    container_name: cockroach
    hostname: cockroach
    image: cockroachdb/cockroach:v20.1.3
    depends_on:
      - kdc
      - roach-cert
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --certs-dir=/certs --listen-addr cockroach
    environment:
      - KRB5_KTNAME=/keytab/crdb.keytab
    volumes:
      - certs-cockroach:/certs
      - keytab:/keytab
    networks:
      roachnet:
        ipv4_address: 172.28.1.4

  client:
    container_name: client
    hostname: client
    build: ./client
    extra_hosts:
      - "cockroach:172.28.1.4"
    depends_on:
      - cockroach
      - kdc
      - roach-cert
    volumes:
      - ./kdc/krb5.conf:/etc/krb5.conf
      - ./client/start.sh:/start.sh
      - certs-client:/certs
      - keytab:/keytab
    networks:
      roachnet:
        ipv4_address: 172.28.1.5

volumes:
  keytab:
  certs-cockroach:
  certs-client:

networks:
  roachnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
