/*
 * This file is generated by jOOQ.
 */
package io.roach.data.jooq.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import io.roach.data.jooq.model.tables.Account;
import io.roach.data.jooq.model.tables.Databasechangelog;
import io.roach.data.jooq.model.tables.Databasechangeloglock;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    private static final long serialVersionUID = 243892754;

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Account.ACCOUNT,
                Databasechangelog.DATABASECHANGELOG,
                Databasechangeloglock.DATABASECHANGELOGLOCK);
    }
}
