/*
 * This file is generated by jOOQ.
 */
package io.roach.data.jooq.model;


import io.roach.data.jooq.model.tables.Account;
import io.roach.data.jooq.model.tables.Databasechangelog;
import io.roach.data.jooq.model.tables.Databasechangeloglock;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;
}
