/*
 * This file is generated by jOOQ.
 */
package com.cockroachlabs.example.jooq.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accounts implements Serializable {

    private static final long serialVersionUID = 890968700;

    private Long id;
    private Long balance;

    public Accounts() {}

    public Accounts(Accounts value) {
        this.id = value.id;
        this.balance = value.balance;
    }

    public Accounts(
        Long id,
        Long balance
    ) {
        this.id = id;
        this.balance = balance;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBalance() {
        return this.balance;
    }

    public void setBalance(Long balance) {
        this.balance = balance;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Accounts (");

        sb.append(id);
        sb.append(", ").append(balance);

        sb.append(")");
        return sb.toString();
    }
}
