/*
 * This file is generated by jOOQ.
 */
package com.cockroachlabs.example.jooq.db;


import com.cockroachlabs.example.jooq.db.tables.Accounts;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNTS</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;
}
